### ISSUE TITLE
After amount of fuel was entered once, it can no longer be disabled 

### ISSUE THREAD

**Issue by philhug** [odch/aircraft-logbook#93]
To reproduce:
set fuel to 10l
delete fuel field
try to save
![Screenshot from 2019-04-16 17-34-44](https://user-images.githubusercontent.com/289201/56223448-0f3f8180-606e-11e9-80e5-1732db0cbc0a.png)

**Comment by rzueger** [comment]
done: https://github.com/odch/aircraft-logbook/pull/134
